# Generated by Django 4.2 on 2024-06-03 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usertemporary_user_type'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.usertemporary'),
        ),
    ]
