# Generated by Django 4.2 on 2024-06-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemporary',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin'), ('DeliveryPerson', 'DeliveryPerson')], max_length=100),
        ),
    ]
