# Generated by Django 4.2 on 2024-06-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usertemporary_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemporary',
            name='user_type',
            field=models.CharField(max_length=100),
        ),
    ]
